Fix: use the proper filesystem which may not be the default
When providing a remote file which does not come from the default
HDFS filesystem, we currently get the following error
java.lang.IllegalArgumentException: Wrong FS: XXX, expected: YYY
The filesystem to use should be selected based on the path.